main: ${mainClass}
name: ${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${project.url}
depend: [${hardDepend}]
softdepend: [${softDepend}]
load: ${loadPhase}
loadbefore: [${loadBefore}]

#################################################################################################
commands:
  votesmanager:
    aliases: [kvotesmanager, votem]
    description: Root command for ${project.name}
    usage: Command not initialised ask admin for help.
  vote:
    description: Open a vote reward inventory.
    aliases: [kvote, votes]
    usage: Command not initialised ask admin for help.
  testvote:
    description: Create test votes.
    aliases: [vtest ktv]
    usage: Command not initialised ask admin for help.

#################################################################################################

permissions:
  keneti.voters.commands.pseudo:
    description: Permission to create pseudo votes.
    default: OP
  keneti.voters.commands.runtask:
    description: Permission to run the reward task.
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  keneti.voters.commands.voteinventory.openself:
    description: Permission to open your vote inventory.
    default: true
  keneti.voters.commands.voteinventory.openothers:
    description: Permission to get the vote inventory of another player.
    default: OP
  keneti.voters.commands.voteinventory.clearothers:
    description: Permission to clear a vote inventory for another player.
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  keneti.voters.features.future:
    description: // TODO
    default: OP
