main: ${mainClass}
name: ${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${project.url}
depend: [${hardDepend}]
softdepend: [${softDepend}]
load: ${loadPhase}
loadbefore: [${loadBefore}]

#################################################################################################
commands:
  quarry:
    aliases: [kquarry]
    description: Root command for ${project.name}
    usage: Command not initialised ask admin for help.
  tpquarry:
    aliases: [tpq]
    description: Teleport to a Quarry.
    usage: Command not initialised ask admin for help.

#################################################################################################

permissions:
  keneti.quarry.*:
    description: Grants access to all ${project.name} Commands and Features.
    default: OP
    children:
      keneti.quarry.commands.*: true
      keneti.quarry.features.*: true
      
#################################################################################################

  keneti.quarry.commands.*:
    description: Grants access to all ${project.name} Commands.
    default: OP
    children:
      keneti.quarry.commands.tpquarry: true
      keneti.quarry.commands.tpquarry.other: true
      #
      #~~~~~~~~~~~~~~~~~~~~~
      
  keneti.quarry.commands.tpquarry:
    description: Teleport to owned quarries.
    default: true
  keneti.quarry.commands.tpquarry.other:
    description: Teleport to other player's quarries.
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  keneti.quarry.features.*:
    description: Grants access to all ${project.name} Features.
    default: OP
    children:
      keneti.quarry.features.future: true
      #
      #~~~~~~~~~~~~~~~~~~~~~
    
  keneti.quarry.features.future:
    description: // TODO
    default: OP
