CREATE TABLE Keneti_Players (
    playerName VARCHAR(32) NOT NULL UNIQUE,
    mojangUUID VARCHAR(36) DEFAULT NULL,
    loginTime BIGINT(13) NOT NULL,    
    lastupdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
        CONSTRAINT pk_playerName PRIMARY KEY (playerName)
)
