main: ${mainClass}
name: ${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${project.url}
depend: [${hardDepend}]
softdepend: [${softDepend}]
load: ${loadPhase}
loadbefore: [${loadBefore}]

#################################################################################################
commands:
  protex:
    aliases: [kprotex]
    description: Root command for ${project.name}
    usage: Command not initialised ask admin for help.

#################################################################################################

permissions:
  keneti.protex.commands.convertclaims:
    description: Convert GP Claims to KC Claims
    default: false
  keneti.protex.commands.clearunused:
    description: Convert GP Claims to KC Claims
    default: false
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  keneti.protex.features.future:
    description: // TODO
    default: OP
