main: ${mainClass}
name: ${artifactId}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${project.url}
depend: [${hardDepend}]
softdepend: [${softDepend}]
load: ${loadPhase}
loadbefore: [${loadBefore}]

#################################################################################################
commands:
  protex:
    aliases: [kprotex]
    description: Root command for ${artifactId}
    usage: Command not initialised ask admin for help.

#################################################################################################

permissions:
  keneti.protex.*:
    description: Grants access to all ${artifactId} Commands and Features.
    default: OP
    children:
      keneti.protex.commands.*: true
      keneti.protex.features.*: true
      
#################################################################################################

  keneti.protex.commands.*:
    description: Grants access to all ${artifactId} Commands.
    default: OP
    children:
      keneti.protex.commands.future: true
      #
      #~~~~~~~~~~~~~~~~~~~~~
      
  keneti.protex.commands.future:
    description: // TODO
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  keneti.protex.features.*:
    description: Grants access to all ${artifactId} Features.
    default: OP
    children:
      keneti.protex.features.future: true
      #
      #~~~~~~~~~~~~~~~~~~~~~
    
  keneti.protex.features.future:
    description: // TODO
    default: OP
