main: ${mainClass}
name: ${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${project.url}
depend: [${hardDepend}]
softdepend: [${softDepend}]
load: ${loadPhase}
loadbefore: [${loadBefore}]

#################################################################################################
commands:
  krandom:
    aliases: [krnd]
    description: Root command for ${project.name}
    usage: Command not initialised ask admin for help.
  growgrass:
    description: Grow Grass!
    aliases: [kgrass, grass]
    usage: Command not initialised ask admin for help.
  itemrename:
    description: Rename held item.
    aliases: [irename]
    usage: Command not initialised ask admin for help.
  enjinnpc:
    description: Keneti Custom Enjin NPC's.
    aliases: [enpc]
    usage: Command not initialised ask admin for help.
  randomteleport:
    description: Teleport to a random location.
    aliases: [krandomteleport, randomtp, rtp]
    usage: Command not initialised ask admin for help.
  endercrystal:
    description: Generate an End EnderCrystal.
    aliases: [kendercrystal, enderc]
    usage: Command not initialised ask admin for help.
  donation:
    description: Used in conjunction with Enjin.
    aliases: [kdon, kdonation]
    usage: Command not initialised ask admin for help.
  serverrestart:
    description: Used in conjunction with Enjin.
    aliases: [kdon, kdonation]
    usage: Command not initialised ask admin for help.

#################################################################################################

permissions:
  keneti.random.commands.growgrass:
    description: Grants access to the /growgrass command.
    default: true
    
  keneti.random.commands.endercrystal:
    description: Grants access to the /endercrystal command.
    default: OP
    
  keneti.random.commands.endercrystal:
    description: Grants access to the /donation command.
    default: false
    
  keneti.random.commands.serverrestart:
    description: Grants access to the /donation command.
    default: false
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  keneti.random.commands.randomteleport.self:
    description: Grants access to the /randomteleport command.
    default: true
  keneti.random.commands.randomteleport.world:
    description: Grants access to the /randomteleport command to use cross world.
    default: true
  keneti.random.commands.randomteleport.others:
    description: Grants access to the /randomteleport command to use on other players.
    default: OP

  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  keneti.random.commands.itemrename.name:
    description: Grants access to the /itemrename name <name> command.
    default: true
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  keneti.random.commands.enpc.podium:
    description: manage podiums.
    default: OP
        
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  keneti.random.features.gamemode.keeponjoin:
    description: On join, keeps gamemode.
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  keneti.random.features.randomteleport.bypass.cost:
    description: No cost for using /rtp
    default: OP
  keneti.random.features.randomteleport.bypass.cooldown:
    description: No cooldown on /rtp
    default: OP
 
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~