main: ${mainClass}
name: ${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${project.url}
depend: [${hardDepend}]
softdepend: [${softDepend}]
load: ${loadPhase}
loadbefore: [${loadBefore}]

#################################################################################################
commands:
  commandplayer:
    aliases: [kcommandplayer, kplayer]
    description: Root command for ${project.name}
    usage: Command not initialised ask admin for help.
  goto:
    aliases: [kgoto, go]
    description: Teleport Server to Server command.
    usage: Command not initialised ask admin for help.
  sendall:
    aliases: [ksendall, kall]
    description: Teleport Server to Server command.
    usage: Command not initialised ask admin for help.
  profiles:
    description: Get your Mojang profile or for another name.
    aliases: [kprofiles, profile, names]
    usage: Command not initialised ask admin for help.
  rankup:
    aliases: [ar, krankup, rank]
    description: Player rank up command.
    usage: Command not initialised ask admin for help.
  objectives:
    aliases: [kobjectives, kobj]
    description: Ranking objectives manager.
    usage: Command not initialised ask admin for help.
  setstaff:
    aliases: [ksetstaff, staff]
    description: Ranking objectives manager.
    usage: Command not initialised ask admin for help.

#################################################################################################

permissions:

  keneti.player.commands.autoranktime:
    description: Sync times between AR and Keneti PlayerData
    default: false
          
#################################################################################################
      
  keneti.player.commands.get:
    description: Get data.
    default: OP
  keneti.player.commands.time.add:
    description: Add time to the players data.
    default: OP
  keneti.player.commands.profiles:
    description: Get a players MC Profile History.
    default: true
  keneti.player.commands.profiles.banned:
    description: Get a players MC Profile History & bypasses check.
    default: true
  keneti.player.commands.setstaff.set:
    description: Set a player as known staff for player based stuff.
    default: false
      
  #~~~~~~~~~~~~~~~~~~~~~~~~~~

  keneti.player.commands.rankup:
    description: Show your personal objectives list.
    default: true
  keneti.player.commands.playtime:
    description: Show your non AFK playtime.
    default: true
  keneti.player.commands.rankup.other:
    description: Show another player's objectives list.
    default: OP
  keneti.player.commands.playtime.other:
    description: Show another player's playtime.
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  keneti.player.commands.objectives.add:
    description: Add a new Objective.
    default: OP
  keneti.player.commands.objectives.remove:
    description: Add a new Objective.
    default: OP
  keneti.player.commands.objectives.reset:
    description: Reset a player's objectives progress.
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  keneti.player.commands.goto.go:
    description: Use the server to server teleport command.
    default: true
    
  keneti.player.commands.goto.list:
    description: List servers that can be teleported to.
    default: true
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  keneti.player.commands.sendall.send:
    description: Use the server to server teleport command.
    default: OP
    
  keneti.player.commands.sendall.list:
    description: List servers that can be teleported to.
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  keneti.player.features.gamemode.creative:
    description: Permission to have Creative Game Mode on the server.
    default: OP
