main: ${mainClass}
name: ${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${project.url}
depend: [${hardDepend}]
softdepend: [${softDepend}]
load: ${loadPhase}
loadbefore: [${loadBefore}]

#################################################################################################
commands:
  outfit:
    aliases: [koutfit]
    description: Root command for ${project.name}
    usage: Command not initialised ask admin for help.

#################################################################################################

permissions:
  keneti.outfit.*:
    description: Grants access to all ${project.name} Commands and Features.
    default: OP
    children:
      keneti.outfit.commands.*: true
      keneti.outfit.features.*: true
      
#################################################################################################

  keneti.outfit.commands.*:
    description: Grants access to all ${project.name} Commands.
    default: OP
    children:
      keneti.outfit.commands.future: true
      #
      #~~~~~~~~~~~~~~~~~~~~~
      
  keneti.outfit.commands.future:
    description:  // TODO
    default: OP
    
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  keneti.outfit.features.*:
    description: Grants access to all ${project.name} Features.
    default: OP
    children:
      keneti.outfit.features.future: true
      #
      #~~~~~~~~~~~~~~~~~~~~~
    
  keneti.outfit.features.future:
    description: // TODO
    default: OP
